### ISSUE TITLE
404 от tmdb при парсинге

### ISSUE THREAD

**Issue by evro23x** [evro23x/kino-domino#64]
Парсим фильм Зверопой
Traceback (most recent call last):
  File "parser_yandex.py", line 328, in <module>
    main()
  File "parser_yandex.py", line 323, in main
    movies_id_list = check_movie_in_db()
  File "parser_yandex.py", line 184, in check_movie_in_db
    movie_info_from_tmdb = get_movie_info_from_tmdb_by_movie_title(movie['event']['title'])
  File "/Users/macpro/projects/startups/kino-domino/request_movie_db.py", line 67, in get_movie_info_from_tmdb_by_movie_title
    movie = get_info_about_movie(movie_id)
  File "/Users/macpro/projects/startups/kino-domino/request_movie_db.py", line 56, in get_info_about_movie
    response = movie.info(language="ru-RU")
  File "/Users/macpro/venvs/kino-domino/lib/python3.5/site-packages/tmdbsimple/movies.py", line 63, in info
    response = self._GET(path, kwargs)
  File "/Users/macpro/venvs/kino-domino/lib/python3.5/site-packages/tmdbsimple/base.py", line 85, in _GET
    return self._request('GET', path, params=params)
  File "/Users/macpro/venvs/kino-domino/lib/python3.5/site-packages/tmdbsimple/base.py", line 80, in _request
    response.raise_for_status()
  File "/Users/macpro/venvs/kino-domino/lib/python3.5/site-packages/requests/models.py", line 831, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found

**Comment by evro23x** [comment]
Видимо лаг tmdb, так как по поиску Зверопой находится, но при переходе по url выдает 404. https://www.themoviedb.org/movie/443782
Нужен обработчик 404-ых.

**Comment by evro23x** [comment]
fix
